### ISSUE TITLE
Concessions

### ISSUE THREAD

**Issue by Aristarkh4** [redguava/cliniko-api#217] opened 2018-03-31 05:43 UTC
Is it possible to add the Student and Elderly concession fields to the billable items request?

**Comment by bpinto** [comment] 2018-04-02 14:12
It shouldn't be a hard entry point to create, but we are overwhelmed with some other feature at the moment, so I don't think we have the time right now to work on this end point.

**Comment by Aristarkh4** [comment] 2018-04-02 22:26
@JohnColvin yes, that's exactly what I was looking for.

**Comment by JohnColvin** [comment] 2018-06-19 20:54
Closing since this is a duplicate of #201

**Closed by JohnColvin** 2018-06-19 20:54 UTC
Labels: duplicate
