### ISSUE TITLE
Treatment notes are not linked to the practitioner_id which I set but to the account which the API key belongs to 

### ISSUE THREAD

**Issue by bafrinrealtimeit** [redguava/cliniko-api#171] opened 2017-07-03 02:14 UTC
I am sending practitioner_id 123 which is DR X with the API Key which happens to be DR Y practitioner_id 456 and the admin, all the notes which belong to DR X with DR Y's name!! 

How can I link the treatment notes to the correct practitioner using Admin API keys?

**Comment by JohnColvin** [comment] 2017-07-05 13:58
Duplicate of this post: https://groups.google.com/a/redguava.com.au/forum/#!topic/cliniko-api/TPZN8WESGF8 and seems to be working now. 

Let us know if you run into any further issues.

**Closed by JohnColvin** 2017-07-05 13:58 UTC
