### ISSUE TITLE
Availability shown for appointment that finishes past the practitioners finishing time

### ISSUE THREAD

**Issue by jontycg** [redguava/cliniko-api#199] opened 2018-01-15 22:47 UTC
I have a practitioner that finishes work at 5:00pm. When using the API to check for availabilities, it said there was an availability at 4:30 pm for an appointment that lasts 45 minutes. This means that the appointment wouldn't finish until 5:15pm, 15 minutes after when the practitioner is scheduled to go home. I was then able to book this using the appointment API.
Attached are images showing the availability request that led to this and the result after booking.

It was the last time in available times that is for an appointment starting at 4:30 pm. My local time is NZT.

<img width="644" alt="screen shot 2018-01-16 at 11 44 09 am" src="https://user-images.githubusercontent.com/10652911/34964495-b1314136-fab2-11e7-861f-e4c560dfdaa7.png">
<img width="1110" alt="screen shot 2018-01-16 at 11 41 38 am" src="https://user-images.githubusercontent.com/10652911/34964503-bd746108-fab2-11e7-89ce-e981cf58433e.png">

Is this a bug or is it intended to function this way?

**Comment by hagen** [comment] 2018-01-15 23:27
Hey Jonty,

in the Cliniko UI, you are able to book appointments that venture in to a
practitioner's unavailable times.
When making such an appointment in the UI, there is a warning that the
appointment is going in to the practitioner's unavailable times. There is
no such warning in the API.

To handle this in your code, you would need to check the practitioner's
availablity, then check the requested timeframe of the appointment. If the
appointment goes over the practitioner's availability, don't make the
appointment. This is clinic-specific business logic, not something that
Cliniko would enforce. Many/most/all clinics allow their practitioners to
work past their availability - usually on a case-by-case basis.

Cheers
Hagen
(I don't work for Cliniko)

**Comment by JohnColvin** [comment] 2018-01-16 16:17
Hey Jonty,

I just had a chat with my co-worker who knows it much better than I do. He confirmed that offering a slot where the appointment extends past the end of the availability is a bug. However, this is a notoriously challenging area to make work well for everyone, so I can't guarantee a quick fix.

Hagen is correct that the API will not do anything to prevent you from booking an appointment that is in an unavailable time since people frequently book themselves in that way. It does make it more of a challenge when the available times offers you a slot that isn't entirely available, though.

**Comment by jontycg** [comment] 2018-01-16 20:12
Hi John,

I definitely agree with you and Hagen that the booking API should allow you to book for any time regardless of availability. 

I am glad to hear that the time slot that runs into unavailable time being shown from the availability API is a bug though. 

Appreciate you looking into it.

**Comment by hagen** [comment] 2019-11-18 21:13
Closing on the basis that there's no _right_ answer here.

We could omit partial availabilities for an appointment type (like this example), but technically there's nothing stopping a user from booking an appointment in a partially available slot, let alone an unavailable slot.

If you don't want your integration to be able to book appointments beyond a prac's availability, that logic is best handled in your code.

Please reopen if required 😊

**Closed by hagen** 2019-11-18 21:13 UTC
